# Generated by Django 5.1.7 on 2025-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='interval_seconds',
            field=models.IntegerField(default=300, help_text='Check interval (30s to 24h)'),
        ),
    ]
